// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bft_messages.proto

#include "bft_messages.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace chronos {
namespace bft {
PROTOBUF_CONSTEXPR SignatureProto::SignatureProto(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.data_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SignatureProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SignatureProtoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SignatureProtoDefaultTypeInternal() {}
  union {
    SignatureProto _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SignatureProtoDefaultTypeInternal _SignatureProto_default_instance_;
PROTOBUF_CONSTEXPR Prevote::Prevote(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.block_hash_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.validator_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.signature_)*/nullptr
  , /*decltype(_impl_.height_)*/uint64_t{0u}
  , /*decltype(_impl_.round_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PrevoteDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PrevoteDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PrevoteDefaultTypeInternal() {}
  union {
    Prevote _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PrevoteDefaultTypeInternal _Prevote_default_instance_;
PROTOBUF_CONSTEXPR Precommit::Precommit(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.block_hash_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.validator_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.signature_)*/nullptr
  , /*decltype(_impl_.height_)*/uint64_t{0u}
  , /*decltype(_impl_.round_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PrecommitDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PrecommitDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PrecommitDefaultTypeInternal() {}
  union {
    Precommit _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PrecommitDefaultTypeInternal _Precommit_default_instance_;
PROTOBUF_CONSTEXPR NewRound::NewRound(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.proposal_block_hash_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.validator_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.signature_)*/nullptr
  , /*decltype(_impl_.height_)*/uint64_t{0u}
  , /*decltype(_impl_.round_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct NewRoundDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NewRoundDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~NewRoundDefaultTypeInternal() {}
  union {
    NewRound _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NewRoundDefaultTypeInternal _NewRound_default_instance_;
}  // namespace bft
}  // namespace chronos
static ::_pb::Metadata file_level_metadata_bft_5fmessages_2eproto[4];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_bft_5fmessages_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_bft_5fmessages_2eproto = nullptr;

const uint32_t TableStruct_bft_5fmessages_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::chronos::bft::SignatureProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::chronos::bft::SignatureProto, _impl_.data_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::chronos::bft::Prevote, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::chronos::bft::Prevote, _impl_.height_),
  PROTOBUF_FIELD_OFFSET(::chronos::bft::Prevote, _impl_.round_),
  PROTOBUF_FIELD_OFFSET(::chronos::bft::Prevote, _impl_.block_hash_),
  PROTOBUF_FIELD_OFFSET(::chronos::bft::Prevote, _impl_.validator_id_),
  PROTOBUF_FIELD_OFFSET(::chronos::bft::Prevote, _impl_.signature_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::chronos::bft::Precommit, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::chronos::bft::Precommit, _impl_.height_),
  PROTOBUF_FIELD_OFFSET(::chronos::bft::Precommit, _impl_.round_),
  PROTOBUF_FIELD_OFFSET(::chronos::bft::Precommit, _impl_.block_hash_),
  PROTOBUF_FIELD_OFFSET(::chronos::bft::Precommit, _impl_.validator_id_),
  PROTOBUF_FIELD_OFFSET(::chronos::bft::Precommit, _impl_.signature_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::chronos::bft::NewRound, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::chronos::bft::NewRound, _impl_.height_),
  PROTOBUF_FIELD_OFFSET(::chronos::bft::NewRound, _impl_.round_),
  PROTOBUF_FIELD_OFFSET(::chronos::bft::NewRound, _impl_.proposal_block_hash_),
  PROTOBUF_FIELD_OFFSET(::chronos::bft::NewRound, _impl_.validator_id_),
  PROTOBUF_FIELD_OFFSET(::chronos::bft::NewRound, _impl_.signature_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::chronos::bft::SignatureProto)},
  { 7, -1, -1, sizeof(::chronos::bft::Prevote)},
  { 18, -1, -1, sizeof(::chronos::bft::Precommit)},
  { 29, -1, -1, sizeof(::chronos::bft::NewRound)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::chronos::bft::_SignatureProto_default_instance_._instance,
  &::chronos::bft::_Prevote_default_instance_._instance,
  &::chronos::bft::_Precommit_default_instance_._instance,
  &::chronos::bft::_NewRound_default_instance_._instance,
};

const char descriptor_table_protodef_bft_5fmessages_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022bft_messages.proto\022\013chronos.bft\"\036\n\016Sig"
  "natureProto\022\014\n\004data\030\001 \001(\014\"\202\001\n\007Prevote\022\016\n"
  "\006height\030\001 \001(\004\022\r\n\005round\030\002 \001(\r\022\022\n\nblock_ha"
  "sh\030\003 \001(\014\022\024\n\014validator_id\030\004 \001(\t\022.\n\tsignat"
  "ure\030\005 \001(\0132\033.chronos.bft.SignatureProto\"\204"
  "\001\n\tPrecommit\022\016\n\006height\030\001 \001(\004\022\r\n\005round\030\002 "
  "\001(\r\022\022\n\nblock_hash\030\003 \001(\014\022\024\n\014validator_id\030"
  "\004 \001(\t\022.\n\tsignature\030\005 \001(\0132\033.chronos.bft.S"
  "ignatureProto\"\214\001\n\010NewRound\022\016\n\006height\030\001 \001"
  "(\004\022\r\n\005round\030\002 \001(\r\022\033\n\023proposal_block_hash"
  "\030\003 \001(\014\022\024\n\014validator_id\030\004 \001(\t\022.\n\tsignatur"
  "e\030\005 \001(\0132\033.chronos.bft.SignatureProtob\006pr"
  "oto3"
  ;
static ::_pbi::once_flag descriptor_table_bft_5fmessages_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_bft_5fmessages_2eproto = {
    false, false, 484, descriptor_table_protodef_bft_5fmessages_2eproto,
    "bft_messages.proto",
    &descriptor_table_bft_5fmessages_2eproto_once, nullptr, 0, 4,
    schemas, file_default_instances, TableStruct_bft_5fmessages_2eproto::offsets,
    file_level_metadata_bft_5fmessages_2eproto, file_level_enum_descriptors_bft_5fmessages_2eproto,
    file_level_service_descriptors_bft_5fmessages_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_bft_5fmessages_2eproto_getter() {
  return &descriptor_table_bft_5fmessages_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_bft_5fmessages_2eproto(&descriptor_table_bft_5fmessages_2eproto);
namespace chronos {
namespace bft {

// ===================================================================

class SignatureProto::_Internal {
 public:
};

SignatureProto::SignatureProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:chronos.bft.SignatureProto)
}
SignatureProto::SignatureProto(const SignatureProto& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SignatureProto* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.data_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_data().empty()) {
    _this->_impl_.data_.Set(from._internal_data(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:chronos.bft.SignatureProto)
}

inline void SignatureProto::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.data_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

SignatureProto::~SignatureProto() {
  // @@protoc_insertion_point(destructor:chronos.bft.SignatureProto)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SignatureProto::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.data_.Destroy();
}

void SignatureProto::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SignatureProto::Clear() {
// @@protoc_insertion_point(message_clear_start:chronos.bft.SignatureProto)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.data_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SignatureProto::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bytes data = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_data();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SignatureProto::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:chronos.bft.SignatureProto)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes data = 1;
  if (!this->_internal_data().empty()) {
    target = stream->WriteBytesMaybeAliased(
        1, this->_internal_data(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:chronos.bft.SignatureProto)
  return target;
}

size_t SignatureProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:chronos.bft.SignatureProto)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes data = 1;
  if (!this->_internal_data().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_data());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SignatureProto::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SignatureProto::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SignatureProto::GetClassData() const { return &_class_data_; }


void SignatureProto::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SignatureProto*>(&to_msg);
  auto& from = static_cast<const SignatureProto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:chronos.bft.SignatureProto)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_data().empty()) {
    _this->_internal_set_data(from._internal_data());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SignatureProto::CopyFrom(const SignatureProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:chronos.bft.SignatureProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SignatureProto::IsInitialized() const {
  return true;
}

void SignatureProto::InternalSwap(SignatureProto* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.data_, lhs_arena,
      &other->_impl_.data_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata SignatureProto::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_bft_5fmessages_2eproto_getter, &descriptor_table_bft_5fmessages_2eproto_once,
      file_level_metadata_bft_5fmessages_2eproto[0]);
}

// ===================================================================

class Prevote::_Internal {
 public:
  static const ::chronos::bft::SignatureProto& signature(const Prevote* msg);
};

const ::chronos::bft::SignatureProto&
Prevote::_Internal::signature(const Prevote* msg) {
  return *msg->_impl_.signature_;
}
Prevote::Prevote(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:chronos.bft.Prevote)
}
Prevote::Prevote(const Prevote& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Prevote* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.block_hash_){}
    , decltype(_impl_.validator_id_){}
    , decltype(_impl_.signature_){nullptr}
    , decltype(_impl_.height_){}
    , decltype(_impl_.round_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.block_hash_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.block_hash_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_block_hash().empty()) {
    _this->_impl_.block_hash_.Set(from._internal_block_hash(), 
      _this->GetArenaForAllocation());
  }
  _impl_.validator_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.validator_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_validator_id().empty()) {
    _this->_impl_.validator_id_.Set(from._internal_validator_id(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_signature()) {
    _this->_impl_.signature_ = new ::chronos::bft::SignatureProto(*from._impl_.signature_);
  }
  ::memcpy(&_impl_.height_, &from._impl_.height_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.round_) -
    reinterpret_cast<char*>(&_impl_.height_)) + sizeof(_impl_.round_));
  // @@protoc_insertion_point(copy_constructor:chronos.bft.Prevote)
}

inline void Prevote::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.block_hash_){}
    , decltype(_impl_.validator_id_){}
    , decltype(_impl_.signature_){nullptr}
    , decltype(_impl_.height_){uint64_t{0u}}
    , decltype(_impl_.round_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.block_hash_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.block_hash_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.validator_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.validator_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Prevote::~Prevote() {
  // @@protoc_insertion_point(destructor:chronos.bft.Prevote)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Prevote::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.block_hash_.Destroy();
  _impl_.validator_id_.Destroy();
  if (this != internal_default_instance()) delete _impl_.signature_;
}

void Prevote::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Prevote::Clear() {
// @@protoc_insertion_point(message_clear_start:chronos.bft.Prevote)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.block_hash_.ClearToEmpty();
  _impl_.validator_id_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.signature_ != nullptr) {
    delete _impl_.signature_;
  }
  _impl_.signature_ = nullptr;
  ::memset(&_impl_.height_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.round_) -
      reinterpret_cast<char*>(&_impl_.height_)) + sizeof(_impl_.round_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Prevote::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 height = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.height_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 round = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.round_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes block_hash = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_block_hash();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string validator_id = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_validator_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "chronos.bft.Prevote.validator_id"));
        } else
          goto handle_unusual;
        continue;
      // .chronos.bft.SignatureProto signature = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_signature(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Prevote::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:chronos.bft.Prevote)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 height = 1;
  if (this->_internal_height() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_height(), target);
  }

  // uint32 round = 2;
  if (this->_internal_round() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_round(), target);
  }

  // bytes block_hash = 3;
  if (!this->_internal_block_hash().empty()) {
    target = stream->WriteBytesMaybeAliased(
        3, this->_internal_block_hash(), target);
  }

  // string validator_id = 4;
  if (!this->_internal_validator_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_validator_id().data(), static_cast<int>(this->_internal_validator_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "chronos.bft.Prevote.validator_id");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_validator_id(), target);
  }

  // .chronos.bft.SignatureProto signature = 5;
  if (this->_internal_has_signature()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, _Internal::signature(this),
        _Internal::signature(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:chronos.bft.Prevote)
  return target;
}

size_t Prevote::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:chronos.bft.Prevote)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes block_hash = 3;
  if (!this->_internal_block_hash().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_block_hash());
  }

  // string validator_id = 4;
  if (!this->_internal_validator_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_validator_id());
  }

  // .chronos.bft.SignatureProto signature = 5;
  if (this->_internal_has_signature()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.signature_);
  }

  // uint64 height = 1;
  if (this->_internal_height() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_height());
  }

  // uint32 round = 2;
  if (this->_internal_round() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_round());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Prevote::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Prevote::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Prevote::GetClassData() const { return &_class_data_; }


void Prevote::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Prevote*>(&to_msg);
  auto& from = static_cast<const Prevote&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:chronos.bft.Prevote)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_block_hash().empty()) {
    _this->_internal_set_block_hash(from._internal_block_hash());
  }
  if (!from._internal_validator_id().empty()) {
    _this->_internal_set_validator_id(from._internal_validator_id());
  }
  if (from._internal_has_signature()) {
    _this->_internal_mutable_signature()->::chronos::bft::SignatureProto::MergeFrom(
        from._internal_signature());
  }
  if (from._internal_height() != 0) {
    _this->_internal_set_height(from._internal_height());
  }
  if (from._internal_round() != 0) {
    _this->_internal_set_round(from._internal_round());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Prevote::CopyFrom(const Prevote& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:chronos.bft.Prevote)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Prevote::IsInitialized() const {
  return true;
}

void Prevote::InternalSwap(Prevote* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.block_hash_, lhs_arena,
      &other->_impl_.block_hash_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.validator_id_, lhs_arena,
      &other->_impl_.validator_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Prevote, _impl_.round_)
      + sizeof(Prevote::_impl_.round_)
      - PROTOBUF_FIELD_OFFSET(Prevote, _impl_.signature_)>(
          reinterpret_cast<char*>(&_impl_.signature_),
          reinterpret_cast<char*>(&other->_impl_.signature_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Prevote::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_bft_5fmessages_2eproto_getter, &descriptor_table_bft_5fmessages_2eproto_once,
      file_level_metadata_bft_5fmessages_2eproto[1]);
}

// ===================================================================

class Precommit::_Internal {
 public:
  static const ::chronos::bft::SignatureProto& signature(const Precommit* msg);
};

const ::chronos::bft::SignatureProto&
Precommit::_Internal::signature(const Precommit* msg) {
  return *msg->_impl_.signature_;
}
Precommit::Precommit(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:chronos.bft.Precommit)
}
Precommit::Precommit(const Precommit& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Precommit* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.block_hash_){}
    , decltype(_impl_.validator_id_){}
    , decltype(_impl_.signature_){nullptr}
    , decltype(_impl_.height_){}
    , decltype(_impl_.round_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.block_hash_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.block_hash_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_block_hash().empty()) {
    _this->_impl_.block_hash_.Set(from._internal_block_hash(), 
      _this->GetArenaForAllocation());
  }
  _impl_.validator_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.validator_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_validator_id().empty()) {
    _this->_impl_.validator_id_.Set(from._internal_validator_id(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_signature()) {
    _this->_impl_.signature_ = new ::chronos::bft::SignatureProto(*from._impl_.signature_);
  }
  ::memcpy(&_impl_.height_, &from._impl_.height_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.round_) -
    reinterpret_cast<char*>(&_impl_.height_)) + sizeof(_impl_.round_));
  // @@protoc_insertion_point(copy_constructor:chronos.bft.Precommit)
}

inline void Precommit::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.block_hash_){}
    , decltype(_impl_.validator_id_){}
    , decltype(_impl_.signature_){nullptr}
    , decltype(_impl_.height_){uint64_t{0u}}
    , decltype(_impl_.round_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.block_hash_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.block_hash_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.validator_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.validator_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Precommit::~Precommit() {
  // @@protoc_insertion_point(destructor:chronos.bft.Precommit)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Precommit::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.block_hash_.Destroy();
  _impl_.validator_id_.Destroy();
  if (this != internal_default_instance()) delete _impl_.signature_;
}

void Precommit::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Precommit::Clear() {
// @@protoc_insertion_point(message_clear_start:chronos.bft.Precommit)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.block_hash_.ClearToEmpty();
  _impl_.validator_id_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.signature_ != nullptr) {
    delete _impl_.signature_;
  }
  _impl_.signature_ = nullptr;
  ::memset(&_impl_.height_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.round_) -
      reinterpret_cast<char*>(&_impl_.height_)) + sizeof(_impl_.round_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Precommit::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 height = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.height_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 round = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.round_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes block_hash = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_block_hash();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string validator_id = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_validator_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "chronos.bft.Precommit.validator_id"));
        } else
          goto handle_unusual;
        continue;
      // .chronos.bft.SignatureProto signature = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_signature(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Precommit::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:chronos.bft.Precommit)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 height = 1;
  if (this->_internal_height() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_height(), target);
  }

  // uint32 round = 2;
  if (this->_internal_round() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_round(), target);
  }

  // bytes block_hash = 3;
  if (!this->_internal_block_hash().empty()) {
    target = stream->WriteBytesMaybeAliased(
        3, this->_internal_block_hash(), target);
  }

  // string validator_id = 4;
  if (!this->_internal_validator_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_validator_id().data(), static_cast<int>(this->_internal_validator_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "chronos.bft.Precommit.validator_id");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_validator_id(), target);
  }

  // .chronos.bft.SignatureProto signature = 5;
  if (this->_internal_has_signature()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, _Internal::signature(this),
        _Internal::signature(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:chronos.bft.Precommit)
  return target;
}

size_t Precommit::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:chronos.bft.Precommit)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes block_hash = 3;
  if (!this->_internal_block_hash().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_block_hash());
  }

  // string validator_id = 4;
  if (!this->_internal_validator_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_validator_id());
  }

  // .chronos.bft.SignatureProto signature = 5;
  if (this->_internal_has_signature()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.signature_);
  }

  // uint64 height = 1;
  if (this->_internal_height() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_height());
  }

  // uint32 round = 2;
  if (this->_internal_round() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_round());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Precommit::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Precommit::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Precommit::GetClassData() const { return &_class_data_; }


void Precommit::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Precommit*>(&to_msg);
  auto& from = static_cast<const Precommit&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:chronos.bft.Precommit)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_block_hash().empty()) {
    _this->_internal_set_block_hash(from._internal_block_hash());
  }
  if (!from._internal_validator_id().empty()) {
    _this->_internal_set_validator_id(from._internal_validator_id());
  }
  if (from._internal_has_signature()) {
    _this->_internal_mutable_signature()->::chronos::bft::SignatureProto::MergeFrom(
        from._internal_signature());
  }
  if (from._internal_height() != 0) {
    _this->_internal_set_height(from._internal_height());
  }
  if (from._internal_round() != 0) {
    _this->_internal_set_round(from._internal_round());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Precommit::CopyFrom(const Precommit& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:chronos.bft.Precommit)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Precommit::IsInitialized() const {
  return true;
}

void Precommit::InternalSwap(Precommit* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.block_hash_, lhs_arena,
      &other->_impl_.block_hash_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.validator_id_, lhs_arena,
      &other->_impl_.validator_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Precommit, _impl_.round_)
      + sizeof(Precommit::_impl_.round_)
      - PROTOBUF_FIELD_OFFSET(Precommit, _impl_.signature_)>(
          reinterpret_cast<char*>(&_impl_.signature_),
          reinterpret_cast<char*>(&other->_impl_.signature_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Precommit::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_bft_5fmessages_2eproto_getter, &descriptor_table_bft_5fmessages_2eproto_once,
      file_level_metadata_bft_5fmessages_2eproto[2]);
}

// ===================================================================

class NewRound::_Internal {
 public:
  static const ::chronos::bft::SignatureProto& signature(const NewRound* msg);
};

const ::chronos::bft::SignatureProto&
NewRound::_Internal::signature(const NewRound* msg) {
  return *msg->_impl_.signature_;
}
NewRound::NewRound(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:chronos.bft.NewRound)
}
NewRound::NewRound(const NewRound& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  NewRound* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.proposal_block_hash_){}
    , decltype(_impl_.validator_id_){}
    , decltype(_impl_.signature_){nullptr}
    , decltype(_impl_.height_){}
    , decltype(_impl_.round_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.proposal_block_hash_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.proposal_block_hash_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_proposal_block_hash().empty()) {
    _this->_impl_.proposal_block_hash_.Set(from._internal_proposal_block_hash(), 
      _this->GetArenaForAllocation());
  }
  _impl_.validator_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.validator_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_validator_id().empty()) {
    _this->_impl_.validator_id_.Set(from._internal_validator_id(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_signature()) {
    _this->_impl_.signature_ = new ::chronos::bft::SignatureProto(*from._impl_.signature_);
  }
  ::memcpy(&_impl_.height_, &from._impl_.height_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.round_) -
    reinterpret_cast<char*>(&_impl_.height_)) + sizeof(_impl_.round_));
  // @@protoc_insertion_point(copy_constructor:chronos.bft.NewRound)
}

inline void NewRound::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.proposal_block_hash_){}
    , decltype(_impl_.validator_id_){}
    , decltype(_impl_.signature_){nullptr}
    , decltype(_impl_.height_){uint64_t{0u}}
    , decltype(_impl_.round_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.proposal_block_hash_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.proposal_block_hash_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.validator_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.validator_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

NewRound::~NewRound() {
  // @@protoc_insertion_point(destructor:chronos.bft.NewRound)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void NewRound::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.proposal_block_hash_.Destroy();
  _impl_.validator_id_.Destroy();
  if (this != internal_default_instance()) delete _impl_.signature_;
}

void NewRound::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void NewRound::Clear() {
// @@protoc_insertion_point(message_clear_start:chronos.bft.NewRound)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.proposal_block_hash_.ClearToEmpty();
  _impl_.validator_id_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.signature_ != nullptr) {
    delete _impl_.signature_;
  }
  _impl_.signature_ = nullptr;
  ::memset(&_impl_.height_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.round_) -
      reinterpret_cast<char*>(&_impl_.height_)) + sizeof(_impl_.round_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* NewRound::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 height = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.height_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 round = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.round_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes proposal_block_hash = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_proposal_block_hash();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string validator_id = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_validator_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "chronos.bft.NewRound.validator_id"));
        } else
          goto handle_unusual;
        continue;
      // .chronos.bft.SignatureProto signature = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_signature(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* NewRound::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:chronos.bft.NewRound)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 height = 1;
  if (this->_internal_height() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_height(), target);
  }

  // uint32 round = 2;
  if (this->_internal_round() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_round(), target);
  }

  // bytes proposal_block_hash = 3;
  if (!this->_internal_proposal_block_hash().empty()) {
    target = stream->WriteBytesMaybeAliased(
        3, this->_internal_proposal_block_hash(), target);
  }

  // string validator_id = 4;
  if (!this->_internal_validator_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_validator_id().data(), static_cast<int>(this->_internal_validator_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "chronos.bft.NewRound.validator_id");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_validator_id(), target);
  }

  // .chronos.bft.SignatureProto signature = 5;
  if (this->_internal_has_signature()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, _Internal::signature(this),
        _Internal::signature(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:chronos.bft.NewRound)
  return target;
}

size_t NewRound::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:chronos.bft.NewRound)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes proposal_block_hash = 3;
  if (!this->_internal_proposal_block_hash().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_proposal_block_hash());
  }

  // string validator_id = 4;
  if (!this->_internal_validator_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_validator_id());
  }

  // .chronos.bft.SignatureProto signature = 5;
  if (this->_internal_has_signature()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.signature_);
  }

  // uint64 height = 1;
  if (this->_internal_height() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_height());
  }

  // uint32 round = 2;
  if (this->_internal_round() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_round());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData NewRound::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    NewRound::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*NewRound::GetClassData() const { return &_class_data_; }


void NewRound::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<NewRound*>(&to_msg);
  auto& from = static_cast<const NewRound&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:chronos.bft.NewRound)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_proposal_block_hash().empty()) {
    _this->_internal_set_proposal_block_hash(from._internal_proposal_block_hash());
  }
  if (!from._internal_validator_id().empty()) {
    _this->_internal_set_validator_id(from._internal_validator_id());
  }
  if (from._internal_has_signature()) {
    _this->_internal_mutable_signature()->::chronos::bft::SignatureProto::MergeFrom(
        from._internal_signature());
  }
  if (from._internal_height() != 0) {
    _this->_internal_set_height(from._internal_height());
  }
  if (from._internal_round() != 0) {
    _this->_internal_set_round(from._internal_round());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void NewRound::CopyFrom(const NewRound& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:chronos.bft.NewRound)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NewRound::IsInitialized() const {
  return true;
}

void NewRound::InternalSwap(NewRound* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.proposal_block_hash_, lhs_arena,
      &other->_impl_.proposal_block_hash_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.validator_id_, lhs_arena,
      &other->_impl_.validator_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(NewRound, _impl_.round_)
      + sizeof(NewRound::_impl_.round_)
      - PROTOBUF_FIELD_OFFSET(NewRound, _impl_.signature_)>(
          reinterpret_cast<char*>(&_impl_.signature_),
          reinterpret_cast<char*>(&other->_impl_.signature_));
}

::PROTOBUF_NAMESPACE_ID::Metadata NewRound::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_bft_5fmessages_2eproto_getter, &descriptor_table_bft_5fmessages_2eproto_once,
      file_level_metadata_bft_5fmessages_2eproto[3]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace bft
}  // namespace chronos
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::chronos::bft::SignatureProto*
Arena::CreateMaybeMessage< ::chronos::bft::SignatureProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::chronos::bft::SignatureProto >(arena);
}
template<> PROTOBUF_NOINLINE ::chronos::bft::Prevote*
Arena::CreateMaybeMessage< ::chronos::bft::Prevote >(Arena* arena) {
  return Arena::CreateMessageInternal< ::chronos::bft::Prevote >(arena);
}
template<> PROTOBUF_NOINLINE ::chronos::bft::Precommit*
Arena::CreateMaybeMessage< ::chronos::bft::Precommit >(Arena* arena) {
  return Arena::CreateMessageInternal< ::chronos::bft::Precommit >(arena);
}
template<> PROTOBUF_NOINLINE ::chronos::bft::NewRound*
Arena::CreateMaybeMessage< ::chronos::bft::NewRound >(Arena* arena) {
  return Arena::CreateMessageInternal< ::chronos::bft::NewRound >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
