// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bft_messages.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_bft_5fmessages_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_bft_5fmessages_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_bft_5fmessages_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_bft_5fmessages_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_bft_5fmessages_2eproto;
namespace chronos {
namespace bft {
class NewRound;
struct NewRoundDefaultTypeInternal;
extern NewRoundDefaultTypeInternal _NewRound_default_instance_;
class Precommit;
struct PrecommitDefaultTypeInternal;
extern PrecommitDefaultTypeInternal _Precommit_default_instance_;
class Prevote;
struct PrevoteDefaultTypeInternal;
extern PrevoteDefaultTypeInternal _Prevote_default_instance_;
class SignatureProto;
struct SignatureProtoDefaultTypeInternal;
extern SignatureProtoDefaultTypeInternal _SignatureProto_default_instance_;
}  // namespace bft
}  // namespace chronos
PROTOBUF_NAMESPACE_OPEN
template<> ::chronos::bft::NewRound* Arena::CreateMaybeMessage<::chronos::bft::NewRound>(Arena*);
template<> ::chronos::bft::Precommit* Arena::CreateMaybeMessage<::chronos::bft::Precommit>(Arena*);
template<> ::chronos::bft::Prevote* Arena::CreateMaybeMessage<::chronos::bft::Prevote>(Arena*);
template<> ::chronos::bft::SignatureProto* Arena::CreateMaybeMessage<::chronos::bft::SignatureProto>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace chronos {
namespace bft {

// ===================================================================

class SignatureProto final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:chronos.bft.SignatureProto) */ {
 public:
  inline SignatureProto() : SignatureProto(nullptr) {}
  ~SignatureProto() override;
  explicit PROTOBUF_CONSTEXPR SignatureProto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SignatureProto(const SignatureProto& from);
  SignatureProto(SignatureProto&& from) noexcept
    : SignatureProto() {
    *this = ::std::move(from);
  }

  inline SignatureProto& operator=(const SignatureProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline SignatureProto& operator=(SignatureProto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SignatureProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const SignatureProto* internal_default_instance() {
    return reinterpret_cast<const SignatureProto*>(
               &_SignatureProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SignatureProto& a, SignatureProto& b) {
    a.Swap(&b);
  }
  inline void Swap(SignatureProto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SignatureProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SignatureProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SignatureProto>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SignatureProto& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SignatureProto& from) {
    SignatureProto::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SignatureProto* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "chronos.bft.SignatureProto";
  }
  protected:
  explicit SignatureProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 1,
  };
  // bytes data = 1;
  void clear_data();
  const std::string& data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_data();
  PROTOBUF_NODISCARD std::string* release_data();
  void set_allocated_data(std::string* data);
  private:
  const std::string& _internal_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_data(const std::string& value);
  std::string* _internal_mutable_data();
  public:

  // @@protoc_insertion_point(class_scope:chronos.bft.SignatureProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_bft_5fmessages_2eproto;
};
// -------------------------------------------------------------------

class Prevote final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:chronos.bft.Prevote) */ {
 public:
  inline Prevote() : Prevote(nullptr) {}
  ~Prevote() override;
  explicit PROTOBUF_CONSTEXPR Prevote(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Prevote(const Prevote& from);
  Prevote(Prevote&& from) noexcept
    : Prevote() {
    *this = ::std::move(from);
  }

  inline Prevote& operator=(const Prevote& from) {
    CopyFrom(from);
    return *this;
  }
  inline Prevote& operator=(Prevote&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Prevote& default_instance() {
    return *internal_default_instance();
  }
  static inline const Prevote* internal_default_instance() {
    return reinterpret_cast<const Prevote*>(
               &_Prevote_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Prevote& a, Prevote& b) {
    a.Swap(&b);
  }
  inline void Swap(Prevote* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Prevote* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Prevote* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Prevote>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Prevote& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Prevote& from) {
    Prevote::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Prevote* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "chronos.bft.Prevote";
  }
  protected:
  explicit Prevote(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBlockHashFieldNumber = 3,
    kValidatorIdFieldNumber = 4,
    kSignatureFieldNumber = 5,
    kHeightFieldNumber = 1,
    kRoundFieldNumber = 2,
    kTimeTierFieldNumber = 6,
  };
  // bytes block_hash = 3;
  void clear_block_hash();
  const std::string& block_hash() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_block_hash(ArgT0&& arg0, ArgT... args);
  std::string* mutable_block_hash();
  PROTOBUF_NODISCARD std::string* release_block_hash();
  void set_allocated_block_hash(std::string* block_hash);
  private:
  const std::string& _internal_block_hash() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_block_hash(const std::string& value);
  std::string* _internal_mutable_block_hash();
  public:

  // string validator_id = 4;
  void clear_validator_id();
  const std::string& validator_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_validator_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_validator_id();
  PROTOBUF_NODISCARD std::string* release_validator_id();
  void set_allocated_validator_id(std::string* validator_id);
  private:
  const std::string& _internal_validator_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_validator_id(const std::string& value);
  std::string* _internal_mutable_validator_id();
  public:

  // .chronos.bft.SignatureProto signature = 5;
  bool has_signature() const;
  private:
  bool _internal_has_signature() const;
  public:
  void clear_signature();
  const ::chronos::bft::SignatureProto& signature() const;
  PROTOBUF_NODISCARD ::chronos::bft::SignatureProto* release_signature();
  ::chronos::bft::SignatureProto* mutable_signature();
  void set_allocated_signature(::chronos::bft::SignatureProto* signature);
  private:
  const ::chronos::bft::SignatureProto& _internal_signature() const;
  ::chronos::bft::SignatureProto* _internal_mutable_signature();
  public:
  void unsafe_arena_set_allocated_signature(
      ::chronos::bft::SignatureProto* signature);
  ::chronos::bft::SignatureProto* unsafe_arena_release_signature();

  // uint64 height = 1;
  void clear_height();
  uint64_t height() const;
  void set_height(uint64_t value);
  private:
  uint64_t _internal_height() const;
  void _internal_set_height(uint64_t value);
  public:

  // uint32 round = 2;
  void clear_round();
  uint32_t round() const;
  void set_round(uint32_t value);
  private:
  uint32_t _internal_round() const;
  void _internal_set_round(uint32_t value);
  public:

  // uint32 time_tier = 6;
  void clear_time_tier();
  uint32_t time_tier() const;
  void set_time_tier(uint32_t value);
  private:
  uint32_t _internal_time_tier() const;
  void _internal_set_time_tier(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:chronos.bft.Prevote)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr block_hash_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr validator_id_;
    ::chronos::bft::SignatureProto* signature_;
    uint64_t height_;
    uint32_t round_;
    uint32_t time_tier_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_bft_5fmessages_2eproto;
};
// -------------------------------------------------------------------

class Precommit final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:chronos.bft.Precommit) */ {
 public:
  inline Precommit() : Precommit(nullptr) {}
  ~Precommit() override;
  explicit PROTOBUF_CONSTEXPR Precommit(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Precommit(const Precommit& from);
  Precommit(Precommit&& from) noexcept
    : Precommit() {
    *this = ::std::move(from);
  }

  inline Precommit& operator=(const Precommit& from) {
    CopyFrom(from);
    return *this;
  }
  inline Precommit& operator=(Precommit&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Precommit& default_instance() {
    return *internal_default_instance();
  }
  static inline const Precommit* internal_default_instance() {
    return reinterpret_cast<const Precommit*>(
               &_Precommit_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Precommit& a, Precommit& b) {
    a.Swap(&b);
  }
  inline void Swap(Precommit* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Precommit* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Precommit* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Precommit>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Precommit& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Precommit& from) {
    Precommit::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Precommit* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "chronos.bft.Precommit";
  }
  protected:
  explicit Precommit(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBlockHashFieldNumber = 3,
    kValidatorIdFieldNumber = 4,
    kSignatureFieldNumber = 5,
    kHeightFieldNumber = 1,
    kRoundFieldNumber = 2,
    kTimeTierFieldNumber = 6,
  };
  // bytes block_hash = 3;
  void clear_block_hash();
  const std::string& block_hash() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_block_hash(ArgT0&& arg0, ArgT... args);
  std::string* mutable_block_hash();
  PROTOBUF_NODISCARD std::string* release_block_hash();
  void set_allocated_block_hash(std::string* block_hash);
  private:
  const std::string& _internal_block_hash() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_block_hash(const std::string& value);
  std::string* _internal_mutable_block_hash();
  public:

  // string validator_id = 4;
  void clear_validator_id();
  const std::string& validator_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_validator_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_validator_id();
  PROTOBUF_NODISCARD std::string* release_validator_id();
  void set_allocated_validator_id(std::string* validator_id);
  private:
  const std::string& _internal_validator_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_validator_id(const std::string& value);
  std::string* _internal_mutable_validator_id();
  public:

  // .chronos.bft.SignatureProto signature = 5;
  bool has_signature() const;
  private:
  bool _internal_has_signature() const;
  public:
  void clear_signature();
  const ::chronos::bft::SignatureProto& signature() const;
  PROTOBUF_NODISCARD ::chronos::bft::SignatureProto* release_signature();
  ::chronos::bft::SignatureProto* mutable_signature();
  void set_allocated_signature(::chronos::bft::SignatureProto* signature);
  private:
  const ::chronos::bft::SignatureProto& _internal_signature() const;
  ::chronos::bft::SignatureProto* _internal_mutable_signature();
  public:
  void unsafe_arena_set_allocated_signature(
      ::chronos::bft::SignatureProto* signature);
  ::chronos::bft::SignatureProto* unsafe_arena_release_signature();

  // uint64 height = 1;
  void clear_height();
  uint64_t height() const;
  void set_height(uint64_t value);
  private:
  uint64_t _internal_height() const;
  void _internal_set_height(uint64_t value);
  public:

  // uint32 round = 2;
  void clear_round();
  uint32_t round() const;
  void set_round(uint32_t value);
  private:
  uint32_t _internal_round() const;
  void _internal_set_round(uint32_t value);
  public:

  // uint32 time_tier = 6;
  void clear_time_tier();
  uint32_t time_tier() const;
  void set_time_tier(uint32_t value);
  private:
  uint32_t _internal_time_tier() const;
  void _internal_set_time_tier(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:chronos.bft.Precommit)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr block_hash_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr validator_id_;
    ::chronos::bft::SignatureProto* signature_;
    uint64_t height_;
    uint32_t round_;
    uint32_t time_tier_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_bft_5fmessages_2eproto;
};
// -------------------------------------------------------------------

class NewRound final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:chronos.bft.NewRound) */ {
 public:
  inline NewRound() : NewRound(nullptr) {}
  ~NewRound() override;
  explicit PROTOBUF_CONSTEXPR NewRound(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  NewRound(const NewRound& from);
  NewRound(NewRound&& from) noexcept
    : NewRound() {
    *this = ::std::move(from);
  }

  inline NewRound& operator=(const NewRound& from) {
    CopyFrom(from);
    return *this;
  }
  inline NewRound& operator=(NewRound&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NewRound& default_instance() {
    return *internal_default_instance();
  }
  static inline const NewRound* internal_default_instance() {
    return reinterpret_cast<const NewRound*>(
               &_NewRound_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(NewRound& a, NewRound& b) {
    a.Swap(&b);
  }
  inline void Swap(NewRound* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NewRound* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NewRound* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<NewRound>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const NewRound& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const NewRound& from) {
    NewRound::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NewRound* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "chronos.bft.NewRound";
  }
  protected:
  explicit NewRound(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kProposalBlockHashFieldNumber = 3,
    kValidatorIdFieldNumber = 4,
    kSignatureFieldNumber = 5,
    kHeightFieldNumber = 1,
    kRoundFieldNumber = 2,
    kTimeTierFieldNumber = 6,
  };
  // bytes proposal_block_hash = 3;
  void clear_proposal_block_hash();
  const std::string& proposal_block_hash() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_proposal_block_hash(ArgT0&& arg0, ArgT... args);
  std::string* mutable_proposal_block_hash();
  PROTOBUF_NODISCARD std::string* release_proposal_block_hash();
  void set_allocated_proposal_block_hash(std::string* proposal_block_hash);
  private:
  const std::string& _internal_proposal_block_hash() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_proposal_block_hash(const std::string& value);
  std::string* _internal_mutable_proposal_block_hash();
  public:

  // string validator_id = 4;
  void clear_validator_id();
  const std::string& validator_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_validator_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_validator_id();
  PROTOBUF_NODISCARD std::string* release_validator_id();
  void set_allocated_validator_id(std::string* validator_id);
  private:
  const std::string& _internal_validator_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_validator_id(const std::string& value);
  std::string* _internal_mutable_validator_id();
  public:

  // .chronos.bft.SignatureProto signature = 5;
  bool has_signature() const;
  private:
  bool _internal_has_signature() const;
  public:
  void clear_signature();
  const ::chronos::bft::SignatureProto& signature() const;
  PROTOBUF_NODISCARD ::chronos::bft::SignatureProto* release_signature();
  ::chronos::bft::SignatureProto* mutable_signature();
  void set_allocated_signature(::chronos::bft::SignatureProto* signature);
  private:
  const ::chronos::bft::SignatureProto& _internal_signature() const;
  ::chronos::bft::SignatureProto* _internal_mutable_signature();
  public:
  void unsafe_arena_set_allocated_signature(
      ::chronos::bft::SignatureProto* signature);
  ::chronos::bft::SignatureProto* unsafe_arena_release_signature();

  // uint64 height = 1;
  void clear_height();
  uint64_t height() const;
  void set_height(uint64_t value);
  private:
  uint64_t _internal_height() const;
  void _internal_set_height(uint64_t value);
  public:

  // uint32 round = 2;
  void clear_round();
  uint32_t round() const;
  void set_round(uint32_t value);
  private:
  uint32_t _internal_round() const;
  void _internal_set_round(uint32_t value);
  public:

  // uint32 time_tier = 6;
  void clear_time_tier();
  uint32_t time_tier() const;
  void set_time_tier(uint32_t value);
  private:
  uint32_t _internal_time_tier() const;
  void _internal_set_time_tier(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:chronos.bft.NewRound)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr proposal_block_hash_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr validator_id_;
    ::chronos::bft::SignatureProto* signature_;
    uint64_t height_;
    uint32_t round_;
    uint32_t time_tier_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_bft_5fmessages_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SignatureProto

// bytes data = 1;
inline void SignatureProto::clear_data() {
  _impl_.data_.ClearToEmpty();
}
inline const std::string& SignatureProto::data() const {
  // @@protoc_insertion_point(field_get:chronos.bft.SignatureProto.data)
  return _internal_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SignatureProto::set_data(ArgT0&& arg0, ArgT... args) {
 
 _impl_.data_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chronos.bft.SignatureProto.data)
}
inline std::string* SignatureProto::mutable_data() {
  std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:chronos.bft.SignatureProto.data)
  return _s;
}
inline const std::string& SignatureProto::_internal_data() const {
  return _impl_.data_.Get();
}
inline void SignatureProto::_internal_set_data(const std::string& value) {
  
  _impl_.data_.Set(value, GetArenaForAllocation());
}
inline std::string* SignatureProto::_internal_mutable_data() {
  
  return _impl_.data_.Mutable(GetArenaForAllocation());
}
inline std::string* SignatureProto::release_data() {
  // @@protoc_insertion_point(field_release:chronos.bft.SignatureProto.data)
  return _impl_.data_.Release();
}
inline void SignatureProto::set_allocated_data(std::string* data) {
  if (data != nullptr) {
    
  } else {
    
  }
  _impl_.data_.SetAllocated(data, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.data_.IsDefault()) {
    _impl_.data_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chronos.bft.SignatureProto.data)
}

// -------------------------------------------------------------------

// Prevote

// uint64 height = 1;
inline void Prevote::clear_height() {
  _impl_.height_ = uint64_t{0u};
}
inline uint64_t Prevote::_internal_height() const {
  return _impl_.height_;
}
inline uint64_t Prevote::height() const {
  // @@protoc_insertion_point(field_get:chronos.bft.Prevote.height)
  return _internal_height();
}
inline void Prevote::_internal_set_height(uint64_t value) {
  
  _impl_.height_ = value;
}
inline void Prevote::set_height(uint64_t value) {
  _internal_set_height(value);
  // @@protoc_insertion_point(field_set:chronos.bft.Prevote.height)
}

// uint32 round = 2;
inline void Prevote::clear_round() {
  _impl_.round_ = 0u;
}
inline uint32_t Prevote::_internal_round() const {
  return _impl_.round_;
}
inline uint32_t Prevote::round() const {
  // @@protoc_insertion_point(field_get:chronos.bft.Prevote.round)
  return _internal_round();
}
inline void Prevote::_internal_set_round(uint32_t value) {
  
  _impl_.round_ = value;
}
inline void Prevote::set_round(uint32_t value) {
  _internal_set_round(value);
  // @@protoc_insertion_point(field_set:chronos.bft.Prevote.round)
}

// bytes block_hash = 3;
inline void Prevote::clear_block_hash() {
  _impl_.block_hash_.ClearToEmpty();
}
inline const std::string& Prevote::block_hash() const {
  // @@protoc_insertion_point(field_get:chronos.bft.Prevote.block_hash)
  return _internal_block_hash();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Prevote::set_block_hash(ArgT0&& arg0, ArgT... args) {
 
 _impl_.block_hash_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chronos.bft.Prevote.block_hash)
}
inline std::string* Prevote::mutable_block_hash() {
  std::string* _s = _internal_mutable_block_hash();
  // @@protoc_insertion_point(field_mutable:chronos.bft.Prevote.block_hash)
  return _s;
}
inline const std::string& Prevote::_internal_block_hash() const {
  return _impl_.block_hash_.Get();
}
inline void Prevote::_internal_set_block_hash(const std::string& value) {
  
  _impl_.block_hash_.Set(value, GetArenaForAllocation());
}
inline std::string* Prevote::_internal_mutable_block_hash() {
  
  return _impl_.block_hash_.Mutable(GetArenaForAllocation());
}
inline std::string* Prevote::release_block_hash() {
  // @@protoc_insertion_point(field_release:chronos.bft.Prevote.block_hash)
  return _impl_.block_hash_.Release();
}
inline void Prevote::set_allocated_block_hash(std::string* block_hash) {
  if (block_hash != nullptr) {
    
  } else {
    
  }
  _impl_.block_hash_.SetAllocated(block_hash, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.block_hash_.IsDefault()) {
    _impl_.block_hash_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chronos.bft.Prevote.block_hash)
}

// string validator_id = 4;
inline void Prevote::clear_validator_id() {
  _impl_.validator_id_.ClearToEmpty();
}
inline const std::string& Prevote::validator_id() const {
  // @@protoc_insertion_point(field_get:chronos.bft.Prevote.validator_id)
  return _internal_validator_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Prevote::set_validator_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.validator_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chronos.bft.Prevote.validator_id)
}
inline std::string* Prevote::mutable_validator_id() {
  std::string* _s = _internal_mutable_validator_id();
  // @@protoc_insertion_point(field_mutable:chronos.bft.Prevote.validator_id)
  return _s;
}
inline const std::string& Prevote::_internal_validator_id() const {
  return _impl_.validator_id_.Get();
}
inline void Prevote::_internal_set_validator_id(const std::string& value) {
  
  _impl_.validator_id_.Set(value, GetArenaForAllocation());
}
inline std::string* Prevote::_internal_mutable_validator_id() {
  
  return _impl_.validator_id_.Mutable(GetArenaForAllocation());
}
inline std::string* Prevote::release_validator_id() {
  // @@protoc_insertion_point(field_release:chronos.bft.Prevote.validator_id)
  return _impl_.validator_id_.Release();
}
inline void Prevote::set_allocated_validator_id(std::string* validator_id) {
  if (validator_id != nullptr) {
    
  } else {
    
  }
  _impl_.validator_id_.SetAllocated(validator_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.validator_id_.IsDefault()) {
    _impl_.validator_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chronos.bft.Prevote.validator_id)
}

// .chronos.bft.SignatureProto signature = 5;
inline bool Prevote::_internal_has_signature() const {
  return this != internal_default_instance() && _impl_.signature_ != nullptr;
}
inline bool Prevote::has_signature() const {
  return _internal_has_signature();
}
inline void Prevote::clear_signature() {
  if (GetArenaForAllocation() == nullptr && _impl_.signature_ != nullptr) {
    delete _impl_.signature_;
  }
  _impl_.signature_ = nullptr;
}
inline const ::chronos::bft::SignatureProto& Prevote::_internal_signature() const {
  const ::chronos::bft::SignatureProto* p = _impl_.signature_;
  return p != nullptr ? *p : reinterpret_cast<const ::chronos::bft::SignatureProto&>(
      ::chronos::bft::_SignatureProto_default_instance_);
}
inline const ::chronos::bft::SignatureProto& Prevote::signature() const {
  // @@protoc_insertion_point(field_get:chronos.bft.Prevote.signature)
  return _internal_signature();
}
inline void Prevote::unsafe_arena_set_allocated_signature(
    ::chronos::bft::SignatureProto* signature) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.signature_);
  }
  _impl_.signature_ = signature;
  if (signature) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:chronos.bft.Prevote.signature)
}
inline ::chronos::bft::SignatureProto* Prevote::release_signature() {
  
  ::chronos::bft::SignatureProto* temp = _impl_.signature_;
  _impl_.signature_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::chronos::bft::SignatureProto* Prevote::unsafe_arena_release_signature() {
  // @@protoc_insertion_point(field_release:chronos.bft.Prevote.signature)
  
  ::chronos::bft::SignatureProto* temp = _impl_.signature_;
  _impl_.signature_ = nullptr;
  return temp;
}
inline ::chronos::bft::SignatureProto* Prevote::_internal_mutable_signature() {
  
  if (_impl_.signature_ == nullptr) {
    auto* p = CreateMaybeMessage<::chronos::bft::SignatureProto>(GetArenaForAllocation());
    _impl_.signature_ = p;
  }
  return _impl_.signature_;
}
inline ::chronos::bft::SignatureProto* Prevote::mutable_signature() {
  ::chronos::bft::SignatureProto* _msg = _internal_mutable_signature();
  // @@protoc_insertion_point(field_mutable:chronos.bft.Prevote.signature)
  return _msg;
}
inline void Prevote::set_allocated_signature(::chronos::bft::SignatureProto* signature) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.signature_;
  }
  if (signature) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(signature);
    if (message_arena != submessage_arena) {
      signature = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, signature, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.signature_ = signature;
  // @@protoc_insertion_point(field_set_allocated:chronos.bft.Prevote.signature)
}

// uint32 time_tier = 6;
inline void Prevote::clear_time_tier() {
  _impl_.time_tier_ = 0u;
}
inline uint32_t Prevote::_internal_time_tier() const {
  return _impl_.time_tier_;
}
inline uint32_t Prevote::time_tier() const {
  // @@protoc_insertion_point(field_get:chronos.bft.Prevote.time_tier)
  return _internal_time_tier();
}
inline void Prevote::_internal_set_time_tier(uint32_t value) {
  
  _impl_.time_tier_ = value;
}
inline void Prevote::set_time_tier(uint32_t value) {
  _internal_set_time_tier(value);
  // @@protoc_insertion_point(field_set:chronos.bft.Prevote.time_tier)
}

// -------------------------------------------------------------------

// Precommit

// uint64 height = 1;
inline void Precommit::clear_height() {
  _impl_.height_ = uint64_t{0u};
}
inline uint64_t Precommit::_internal_height() const {
  return _impl_.height_;
}
inline uint64_t Precommit::height() const {
  // @@protoc_insertion_point(field_get:chronos.bft.Precommit.height)
  return _internal_height();
}
inline void Precommit::_internal_set_height(uint64_t value) {
  
  _impl_.height_ = value;
}
inline void Precommit::set_height(uint64_t value) {
  _internal_set_height(value);
  // @@protoc_insertion_point(field_set:chronos.bft.Precommit.height)
}

// uint32 round = 2;
inline void Precommit::clear_round() {
  _impl_.round_ = 0u;
}
inline uint32_t Precommit::_internal_round() const {
  return _impl_.round_;
}
inline uint32_t Precommit::round() const {
  // @@protoc_insertion_point(field_get:chronos.bft.Precommit.round)
  return _internal_round();
}
inline void Precommit::_internal_set_round(uint32_t value) {
  
  _impl_.round_ = value;
}
inline void Precommit::set_round(uint32_t value) {
  _internal_set_round(value);
  // @@protoc_insertion_point(field_set:chronos.bft.Precommit.round)
}

// bytes block_hash = 3;
inline void Precommit::clear_block_hash() {
  _impl_.block_hash_.ClearToEmpty();
}
inline const std::string& Precommit::block_hash() const {
  // @@protoc_insertion_point(field_get:chronos.bft.Precommit.block_hash)
  return _internal_block_hash();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Precommit::set_block_hash(ArgT0&& arg0, ArgT... args) {
 
 _impl_.block_hash_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chronos.bft.Precommit.block_hash)
}
inline std::string* Precommit::mutable_block_hash() {
  std::string* _s = _internal_mutable_block_hash();
  // @@protoc_insertion_point(field_mutable:chronos.bft.Precommit.block_hash)
  return _s;
}
inline const std::string& Precommit::_internal_block_hash() const {
  return _impl_.block_hash_.Get();
}
inline void Precommit::_internal_set_block_hash(const std::string& value) {
  
  _impl_.block_hash_.Set(value, GetArenaForAllocation());
}
inline std::string* Precommit::_internal_mutable_block_hash() {
  
  return _impl_.block_hash_.Mutable(GetArenaForAllocation());
}
inline std::string* Precommit::release_block_hash() {
  // @@protoc_insertion_point(field_release:chronos.bft.Precommit.block_hash)
  return _impl_.block_hash_.Release();
}
inline void Precommit::set_allocated_block_hash(std::string* block_hash) {
  if (block_hash != nullptr) {
    
  } else {
    
  }
  _impl_.block_hash_.SetAllocated(block_hash, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.block_hash_.IsDefault()) {
    _impl_.block_hash_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chronos.bft.Precommit.block_hash)
}

// string validator_id = 4;
inline void Precommit::clear_validator_id() {
  _impl_.validator_id_.ClearToEmpty();
}
inline const std::string& Precommit::validator_id() const {
  // @@protoc_insertion_point(field_get:chronos.bft.Precommit.validator_id)
  return _internal_validator_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Precommit::set_validator_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.validator_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chronos.bft.Precommit.validator_id)
}
inline std::string* Precommit::mutable_validator_id() {
  std::string* _s = _internal_mutable_validator_id();
  // @@protoc_insertion_point(field_mutable:chronos.bft.Precommit.validator_id)
  return _s;
}
inline const std::string& Precommit::_internal_validator_id() const {
  return _impl_.validator_id_.Get();
}
inline void Precommit::_internal_set_validator_id(const std::string& value) {
  
  _impl_.validator_id_.Set(value, GetArenaForAllocation());
}
inline std::string* Precommit::_internal_mutable_validator_id() {
  
  return _impl_.validator_id_.Mutable(GetArenaForAllocation());
}
inline std::string* Precommit::release_validator_id() {
  // @@protoc_insertion_point(field_release:chronos.bft.Precommit.validator_id)
  return _impl_.validator_id_.Release();
}
inline void Precommit::set_allocated_validator_id(std::string* validator_id) {
  if (validator_id != nullptr) {
    
  } else {
    
  }
  _impl_.validator_id_.SetAllocated(validator_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.validator_id_.IsDefault()) {
    _impl_.validator_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chronos.bft.Precommit.validator_id)
}

// .chronos.bft.SignatureProto signature = 5;
inline bool Precommit::_internal_has_signature() const {
  return this != internal_default_instance() && _impl_.signature_ != nullptr;
}
inline bool Precommit::has_signature() const {
  return _internal_has_signature();
}
inline void Precommit::clear_signature() {
  if (GetArenaForAllocation() == nullptr && _impl_.signature_ != nullptr) {
    delete _impl_.signature_;
  }
  _impl_.signature_ = nullptr;
}
inline const ::chronos::bft::SignatureProto& Precommit::_internal_signature() const {
  const ::chronos::bft::SignatureProto* p = _impl_.signature_;
  return p != nullptr ? *p : reinterpret_cast<const ::chronos::bft::SignatureProto&>(
      ::chronos::bft::_SignatureProto_default_instance_);
}
inline const ::chronos::bft::SignatureProto& Precommit::signature() const {
  // @@protoc_insertion_point(field_get:chronos.bft.Precommit.signature)
  return _internal_signature();
}
inline void Precommit::unsafe_arena_set_allocated_signature(
    ::chronos::bft::SignatureProto* signature) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.signature_);
  }
  _impl_.signature_ = signature;
  if (signature) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:chronos.bft.Precommit.signature)
}
inline ::chronos::bft::SignatureProto* Precommit::release_signature() {
  
  ::chronos::bft::SignatureProto* temp = _impl_.signature_;
  _impl_.signature_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::chronos::bft::SignatureProto* Precommit::unsafe_arena_release_signature() {
  // @@protoc_insertion_point(field_release:chronos.bft.Precommit.signature)
  
  ::chronos::bft::SignatureProto* temp = _impl_.signature_;
  _impl_.signature_ = nullptr;
  return temp;
}
inline ::chronos::bft::SignatureProto* Precommit::_internal_mutable_signature() {
  
  if (_impl_.signature_ == nullptr) {
    auto* p = CreateMaybeMessage<::chronos::bft::SignatureProto>(GetArenaForAllocation());
    _impl_.signature_ = p;
  }
  return _impl_.signature_;
}
inline ::chronos::bft::SignatureProto* Precommit::mutable_signature() {
  ::chronos::bft::SignatureProto* _msg = _internal_mutable_signature();
  // @@protoc_insertion_point(field_mutable:chronos.bft.Precommit.signature)
  return _msg;
}
inline void Precommit::set_allocated_signature(::chronos::bft::SignatureProto* signature) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.signature_;
  }
  if (signature) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(signature);
    if (message_arena != submessage_arena) {
      signature = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, signature, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.signature_ = signature;
  // @@protoc_insertion_point(field_set_allocated:chronos.bft.Precommit.signature)
}

// uint32 time_tier = 6;
inline void Precommit::clear_time_tier() {
  _impl_.time_tier_ = 0u;
}
inline uint32_t Precommit::_internal_time_tier() const {
  return _impl_.time_tier_;
}
inline uint32_t Precommit::time_tier() const {
  // @@protoc_insertion_point(field_get:chronos.bft.Precommit.time_tier)
  return _internal_time_tier();
}
inline void Precommit::_internal_set_time_tier(uint32_t value) {
  
  _impl_.time_tier_ = value;
}
inline void Precommit::set_time_tier(uint32_t value) {
  _internal_set_time_tier(value);
  // @@protoc_insertion_point(field_set:chronos.bft.Precommit.time_tier)
}

// -------------------------------------------------------------------

// NewRound

// uint64 height = 1;
inline void NewRound::clear_height() {
  _impl_.height_ = uint64_t{0u};
}
inline uint64_t NewRound::_internal_height() const {
  return _impl_.height_;
}
inline uint64_t NewRound::height() const {
  // @@protoc_insertion_point(field_get:chronos.bft.NewRound.height)
  return _internal_height();
}
inline void NewRound::_internal_set_height(uint64_t value) {
  
  _impl_.height_ = value;
}
inline void NewRound::set_height(uint64_t value) {
  _internal_set_height(value);
  // @@protoc_insertion_point(field_set:chronos.bft.NewRound.height)
}

// uint32 round = 2;
inline void NewRound::clear_round() {
  _impl_.round_ = 0u;
}
inline uint32_t NewRound::_internal_round() const {
  return _impl_.round_;
}
inline uint32_t NewRound::round() const {
  // @@protoc_insertion_point(field_get:chronos.bft.NewRound.round)
  return _internal_round();
}
inline void NewRound::_internal_set_round(uint32_t value) {
  
  _impl_.round_ = value;
}
inline void NewRound::set_round(uint32_t value) {
  _internal_set_round(value);
  // @@protoc_insertion_point(field_set:chronos.bft.NewRound.round)
}

// bytes proposal_block_hash = 3;
inline void NewRound::clear_proposal_block_hash() {
  _impl_.proposal_block_hash_.ClearToEmpty();
}
inline const std::string& NewRound::proposal_block_hash() const {
  // @@protoc_insertion_point(field_get:chronos.bft.NewRound.proposal_block_hash)
  return _internal_proposal_block_hash();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void NewRound::set_proposal_block_hash(ArgT0&& arg0, ArgT... args) {
 
 _impl_.proposal_block_hash_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chronos.bft.NewRound.proposal_block_hash)
}
inline std::string* NewRound::mutable_proposal_block_hash() {
  std::string* _s = _internal_mutable_proposal_block_hash();
  // @@protoc_insertion_point(field_mutable:chronos.bft.NewRound.proposal_block_hash)
  return _s;
}
inline const std::string& NewRound::_internal_proposal_block_hash() const {
  return _impl_.proposal_block_hash_.Get();
}
inline void NewRound::_internal_set_proposal_block_hash(const std::string& value) {
  
  _impl_.proposal_block_hash_.Set(value, GetArenaForAllocation());
}
inline std::string* NewRound::_internal_mutable_proposal_block_hash() {
  
  return _impl_.proposal_block_hash_.Mutable(GetArenaForAllocation());
}
inline std::string* NewRound::release_proposal_block_hash() {
  // @@protoc_insertion_point(field_release:chronos.bft.NewRound.proposal_block_hash)
  return _impl_.proposal_block_hash_.Release();
}
inline void NewRound::set_allocated_proposal_block_hash(std::string* proposal_block_hash) {
  if (proposal_block_hash != nullptr) {
    
  } else {
    
  }
  _impl_.proposal_block_hash_.SetAllocated(proposal_block_hash, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.proposal_block_hash_.IsDefault()) {
    _impl_.proposal_block_hash_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chronos.bft.NewRound.proposal_block_hash)
}

// string validator_id = 4;
inline void NewRound::clear_validator_id() {
  _impl_.validator_id_.ClearToEmpty();
}
inline const std::string& NewRound::validator_id() const {
  // @@protoc_insertion_point(field_get:chronos.bft.NewRound.validator_id)
  return _internal_validator_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void NewRound::set_validator_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.validator_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chronos.bft.NewRound.validator_id)
}
inline std::string* NewRound::mutable_validator_id() {
  std::string* _s = _internal_mutable_validator_id();
  // @@protoc_insertion_point(field_mutable:chronos.bft.NewRound.validator_id)
  return _s;
}
inline const std::string& NewRound::_internal_validator_id() const {
  return _impl_.validator_id_.Get();
}
inline void NewRound::_internal_set_validator_id(const std::string& value) {
  
  _impl_.validator_id_.Set(value, GetArenaForAllocation());
}
inline std::string* NewRound::_internal_mutable_validator_id() {
  
  return _impl_.validator_id_.Mutable(GetArenaForAllocation());
}
inline std::string* NewRound::release_validator_id() {
  // @@protoc_insertion_point(field_release:chronos.bft.NewRound.validator_id)
  return _impl_.validator_id_.Release();
}
inline void NewRound::set_allocated_validator_id(std::string* validator_id) {
  if (validator_id != nullptr) {
    
  } else {
    
  }
  _impl_.validator_id_.SetAllocated(validator_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.validator_id_.IsDefault()) {
    _impl_.validator_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chronos.bft.NewRound.validator_id)
}

// .chronos.bft.SignatureProto signature = 5;
inline bool NewRound::_internal_has_signature() const {
  return this != internal_default_instance() && _impl_.signature_ != nullptr;
}
inline bool NewRound::has_signature() const {
  return _internal_has_signature();
}
inline void NewRound::clear_signature() {
  if (GetArenaForAllocation() == nullptr && _impl_.signature_ != nullptr) {
    delete _impl_.signature_;
  }
  _impl_.signature_ = nullptr;
}
inline const ::chronos::bft::SignatureProto& NewRound::_internal_signature() const {
  const ::chronos::bft::SignatureProto* p = _impl_.signature_;
  return p != nullptr ? *p : reinterpret_cast<const ::chronos::bft::SignatureProto&>(
      ::chronos::bft::_SignatureProto_default_instance_);
}
inline const ::chronos::bft::SignatureProto& NewRound::signature() const {
  // @@protoc_insertion_point(field_get:chronos.bft.NewRound.signature)
  return _internal_signature();
}
inline void NewRound::unsafe_arena_set_allocated_signature(
    ::chronos::bft::SignatureProto* signature) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.signature_);
  }
  _impl_.signature_ = signature;
  if (signature) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:chronos.bft.NewRound.signature)
}
inline ::chronos::bft::SignatureProto* NewRound::release_signature() {
  
  ::chronos::bft::SignatureProto* temp = _impl_.signature_;
  _impl_.signature_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::chronos::bft::SignatureProto* NewRound::unsafe_arena_release_signature() {
  // @@protoc_insertion_point(field_release:chronos.bft.NewRound.signature)
  
  ::chronos::bft::SignatureProto* temp = _impl_.signature_;
  _impl_.signature_ = nullptr;
  return temp;
}
inline ::chronos::bft::SignatureProto* NewRound::_internal_mutable_signature() {
  
  if (_impl_.signature_ == nullptr) {
    auto* p = CreateMaybeMessage<::chronos::bft::SignatureProto>(GetArenaForAllocation());
    _impl_.signature_ = p;
  }
  return _impl_.signature_;
}
inline ::chronos::bft::SignatureProto* NewRound::mutable_signature() {
  ::chronos::bft::SignatureProto* _msg = _internal_mutable_signature();
  // @@protoc_insertion_point(field_mutable:chronos.bft.NewRound.signature)
  return _msg;
}
inline void NewRound::set_allocated_signature(::chronos::bft::SignatureProto* signature) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.signature_;
  }
  if (signature) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(signature);
    if (message_arena != submessage_arena) {
      signature = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, signature, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.signature_ = signature;
  // @@protoc_insertion_point(field_set_allocated:chronos.bft.NewRound.signature)
}

// uint32 time_tier = 6;
inline void NewRound::clear_time_tier() {
  _impl_.time_tier_ = 0u;
}
inline uint32_t NewRound::_internal_time_tier() const {
  return _impl_.time_tier_;
}
inline uint32_t NewRound::time_tier() const {
  // @@protoc_insertion_point(field_get:chronos.bft.NewRound.time_tier)
  return _internal_time_tier();
}
inline void NewRound::_internal_set_time_tier(uint32_t value) {
  
  _impl_.time_tier_ = value;
}
inline void NewRound::set_time_tier(uint32_t value) {
  _internal_set_time_tier(value);
  // @@protoc_insertion_point(field_set:chronos.bft.NewRound.time_tier)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace bft
}  // namespace chronos

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_bft_5fmessages_2eproto
