// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ledger.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ledger_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ledger_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ledger_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ledger_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ledger_2eproto;
namespace chrono_ledger_proto {
class Block;
struct BlockDefaultTypeInternal;
extern BlockDefaultTypeInternal _Block_default_instance_;
class Transaction;
struct TransactionDefaultTypeInternal;
extern TransactionDefaultTypeInternal _Transaction_default_instance_;
}  // namespace chrono_ledger_proto
PROTOBUF_NAMESPACE_OPEN
template<> ::chrono_ledger_proto::Block* Arena::CreateMaybeMessage<::chrono_ledger_proto::Block>(Arena*);
template<> ::chrono_ledger_proto::Transaction* Arena::CreateMaybeMessage<::chrono_ledger_proto::Transaction>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace chrono_ledger_proto {

// ===================================================================

class Transaction final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:chrono_ledger_proto.Transaction) */ {
 public:
  inline Transaction() : Transaction(nullptr) {}
  ~Transaction() override;
  explicit PROTOBUF_CONSTEXPR Transaction(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Transaction(const Transaction& from);
  Transaction(Transaction&& from) noexcept
    : Transaction() {
    *this = ::std::move(from);
  }

  inline Transaction& operator=(const Transaction& from) {
    CopyFrom(from);
    return *this;
  }
  inline Transaction& operator=(Transaction&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Transaction& default_instance() {
    return *internal_default_instance();
  }
  static inline const Transaction* internal_default_instance() {
    return reinterpret_cast<const Transaction*>(
               &_Transaction_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Transaction& a, Transaction& b) {
    a.Swap(&b);
  }
  inline void Swap(Transaction* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Transaction* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Transaction* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Transaction>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Transaction& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Transaction& from) {
    Transaction::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Transaction* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "chrono_ledger_proto.Transaction";
  }
  protected:
  explicit Transaction(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSenderFieldNumber = 2,
    kRecipientFieldNumber = 3,
    kPayloadFieldNumber = 7,
    kSignatureFieldNumber = 8,
    kAmountFieldNumber = 4,
    kFeeFieldNumber = 5,
    kNonceFieldNumber = 6,
    kTypeFieldNumber = 1,
  };
  // string sender = 2;
  void clear_sender();
  const std::string& sender() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_sender(ArgT0&& arg0, ArgT... args);
  std::string* mutable_sender();
  PROTOBUF_NODISCARD std::string* release_sender();
  void set_allocated_sender(std::string* sender);
  private:
  const std::string& _internal_sender() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sender(const std::string& value);
  std::string* _internal_mutable_sender();
  public:

  // string recipient = 3;
  void clear_recipient();
  const std::string& recipient() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_recipient(ArgT0&& arg0, ArgT... args);
  std::string* mutable_recipient();
  PROTOBUF_NODISCARD std::string* release_recipient();
  void set_allocated_recipient(std::string* recipient);
  private:
  const std::string& _internal_recipient() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_recipient(const std::string& value);
  std::string* _internal_mutable_recipient();
  public:

  // bytes payload = 7;
  void clear_payload();
  const std::string& payload() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_payload(ArgT0&& arg0, ArgT... args);
  std::string* mutable_payload();
  PROTOBUF_NODISCARD std::string* release_payload();
  void set_allocated_payload(std::string* payload);
  private:
  const std::string& _internal_payload() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_payload(const std::string& value);
  std::string* _internal_mutable_payload();
  public:

  // bytes signature = 8;
  void clear_signature();
  const std::string& signature() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_signature(ArgT0&& arg0, ArgT... args);
  std::string* mutable_signature();
  PROTOBUF_NODISCARD std::string* release_signature();
  void set_allocated_signature(std::string* signature);
  private:
  const std::string& _internal_signature() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_signature(const std::string& value);
  std::string* _internal_mutable_signature();
  public:

  // uint64 amount = 4;
  void clear_amount();
  uint64_t amount() const;
  void set_amount(uint64_t value);
  private:
  uint64_t _internal_amount() const;
  void _internal_set_amount(uint64_t value);
  public:

  // uint64 fee = 5;
  void clear_fee();
  uint64_t fee() const;
  void set_fee(uint64_t value);
  private:
  uint64_t _internal_fee() const;
  void _internal_set_fee(uint64_t value);
  public:

  // uint64 nonce = 6;
  void clear_nonce();
  uint64_t nonce() const;
  void set_nonce(uint64_t value);
  private:
  uint64_t _internal_nonce() const;
  void _internal_set_nonce(uint64_t value);
  public:

  // uint32 type = 1;
  void clear_type();
  uint32_t type() const;
  void set_type(uint32_t value);
  private:
  uint32_t _internal_type() const;
  void _internal_set_type(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:chrono_ledger_proto.Transaction)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sender_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr recipient_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr payload_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr signature_;
    uint64_t amount_;
    uint64_t fee_;
    uint64_t nonce_;
    uint32_t type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ledger_2eproto;
};
// -------------------------------------------------------------------

class Block final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:chrono_ledger_proto.Block) */ {
 public:
  inline Block() : Block(nullptr) {}
  ~Block() override;
  explicit PROTOBUF_CONSTEXPR Block(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Block(const Block& from);
  Block(Block&& from) noexcept
    : Block() {
    *this = ::std::move(from);
  }

  inline Block& operator=(const Block& from) {
    CopyFrom(from);
    return *this;
  }
  inline Block& operator=(Block&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Block& default_instance() {
    return *internal_default_instance();
  }
  static inline const Block* internal_default_instance() {
    return reinterpret_cast<const Block*>(
               &_Block_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Block& a, Block& b) {
    a.Swap(&b);
  }
  inline void Swap(Block* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Block* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Block* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Block>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Block& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Block& from) {
    Block::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Block* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "chrono_ledger_proto.Block";
  }
  protected:
  explicit Block(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTransactionsFieldNumber = 7,
    kPrevBlockHashFieldNumber = 1,
    kTransactionsMerkleRootFieldNumber = 3,
    kTimestampFieldNumber = 2,
    kHeightFieldNumber = 4,
    kConsensusTimeFieldNumber = 5,
    kRoundFieldNumber = 6,
    kTimeTierFieldNumber = 8,
    kTimeQualityScoreFieldNumber = 9,
  };
  // repeated .chrono_ledger_proto.Transaction transactions = 7;
  int transactions_size() const;
  private:
  int _internal_transactions_size() const;
  public:
  void clear_transactions();
  ::chrono_ledger_proto::Transaction* mutable_transactions(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::chrono_ledger_proto::Transaction >*
      mutable_transactions();
  private:
  const ::chrono_ledger_proto::Transaction& _internal_transactions(int index) const;
  ::chrono_ledger_proto::Transaction* _internal_add_transactions();
  public:
  const ::chrono_ledger_proto::Transaction& transactions(int index) const;
  ::chrono_ledger_proto::Transaction* add_transactions();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::chrono_ledger_proto::Transaction >&
      transactions() const;

  // bytes prev_block_hash = 1;
  void clear_prev_block_hash();
  const std::string& prev_block_hash() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_prev_block_hash(ArgT0&& arg0, ArgT... args);
  std::string* mutable_prev_block_hash();
  PROTOBUF_NODISCARD std::string* release_prev_block_hash();
  void set_allocated_prev_block_hash(std::string* prev_block_hash);
  private:
  const std::string& _internal_prev_block_hash() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_prev_block_hash(const std::string& value);
  std::string* _internal_mutable_prev_block_hash();
  public:

  // bytes transactions_merkle_root = 3;
  void clear_transactions_merkle_root();
  const std::string& transactions_merkle_root() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_transactions_merkle_root(ArgT0&& arg0, ArgT... args);
  std::string* mutable_transactions_merkle_root();
  PROTOBUF_NODISCARD std::string* release_transactions_merkle_root();
  void set_allocated_transactions_merkle_root(std::string* transactions_merkle_root);
  private:
  const std::string& _internal_transactions_merkle_root() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_transactions_merkle_root(const std::string& value);
  std::string* _internal_mutable_transactions_merkle_root();
  public:

  // uint64 timestamp = 2;
  void clear_timestamp();
  uint64_t timestamp() const;
  void set_timestamp(uint64_t value);
  private:
  uint64_t _internal_timestamp() const;
  void _internal_set_timestamp(uint64_t value);
  public:

  // uint64 height = 4;
  void clear_height();
  uint64_t height() const;
  void set_height(uint64_t value);
  private:
  uint64_t _internal_height() const;
  void _internal_set_height(uint64_t value);
  public:

  // uint64 consensus_time = 5;
  void clear_consensus_time();
  uint64_t consensus_time() const;
  void set_consensus_time(uint64_t value);
  private:
  uint64_t _internal_consensus_time() const;
  void _internal_set_consensus_time(uint64_t value);
  public:

  // uint32 round = 6;
  void clear_round();
  uint32_t round() const;
  void set_round(uint32_t value);
  private:
  uint32_t _internal_round() const;
  void _internal_set_round(uint32_t value);
  public:

  // uint32 time_tier = 8;
  void clear_time_tier();
  uint32_t time_tier() const;
  void set_time_tier(uint32_t value);
  private:
  uint32_t _internal_time_tier() const;
  void _internal_set_time_tier(uint32_t value);
  public:

  // uint32 time_quality_score = 9;
  void clear_time_quality_score();
  uint32_t time_quality_score() const;
  void set_time_quality_score(uint32_t value);
  private:
  uint32_t _internal_time_quality_score() const;
  void _internal_set_time_quality_score(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:chrono_ledger_proto.Block)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::chrono_ledger_proto::Transaction > transactions_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr prev_block_hash_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr transactions_merkle_root_;
    uint64_t timestamp_;
    uint64_t height_;
    uint64_t consensus_time_;
    uint32_t round_;
    uint32_t time_tier_;
    uint32_t time_quality_score_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ledger_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Transaction

// uint32 type = 1;
inline void Transaction::clear_type() {
  _impl_.type_ = 0u;
}
inline uint32_t Transaction::_internal_type() const {
  return _impl_.type_;
}
inline uint32_t Transaction::type() const {
  // @@protoc_insertion_point(field_get:chrono_ledger_proto.Transaction.type)
  return _internal_type();
}
inline void Transaction::_internal_set_type(uint32_t value) {
  
  _impl_.type_ = value;
}
inline void Transaction::set_type(uint32_t value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:chrono_ledger_proto.Transaction.type)
}

// string sender = 2;
inline void Transaction::clear_sender() {
  _impl_.sender_.ClearToEmpty();
}
inline const std::string& Transaction::sender() const {
  // @@protoc_insertion_point(field_get:chrono_ledger_proto.Transaction.sender)
  return _internal_sender();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Transaction::set_sender(ArgT0&& arg0, ArgT... args) {
 
 _impl_.sender_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chrono_ledger_proto.Transaction.sender)
}
inline std::string* Transaction::mutable_sender() {
  std::string* _s = _internal_mutable_sender();
  // @@protoc_insertion_point(field_mutable:chrono_ledger_proto.Transaction.sender)
  return _s;
}
inline const std::string& Transaction::_internal_sender() const {
  return _impl_.sender_.Get();
}
inline void Transaction::_internal_set_sender(const std::string& value) {
  
  _impl_.sender_.Set(value, GetArenaForAllocation());
}
inline std::string* Transaction::_internal_mutable_sender() {
  
  return _impl_.sender_.Mutable(GetArenaForAllocation());
}
inline std::string* Transaction::release_sender() {
  // @@protoc_insertion_point(field_release:chrono_ledger_proto.Transaction.sender)
  return _impl_.sender_.Release();
}
inline void Transaction::set_allocated_sender(std::string* sender) {
  if (sender != nullptr) {
    
  } else {
    
  }
  _impl_.sender_.SetAllocated(sender, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.sender_.IsDefault()) {
    _impl_.sender_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chrono_ledger_proto.Transaction.sender)
}

// string recipient = 3;
inline void Transaction::clear_recipient() {
  _impl_.recipient_.ClearToEmpty();
}
inline const std::string& Transaction::recipient() const {
  // @@protoc_insertion_point(field_get:chrono_ledger_proto.Transaction.recipient)
  return _internal_recipient();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Transaction::set_recipient(ArgT0&& arg0, ArgT... args) {
 
 _impl_.recipient_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chrono_ledger_proto.Transaction.recipient)
}
inline std::string* Transaction::mutable_recipient() {
  std::string* _s = _internal_mutable_recipient();
  // @@protoc_insertion_point(field_mutable:chrono_ledger_proto.Transaction.recipient)
  return _s;
}
inline const std::string& Transaction::_internal_recipient() const {
  return _impl_.recipient_.Get();
}
inline void Transaction::_internal_set_recipient(const std::string& value) {
  
  _impl_.recipient_.Set(value, GetArenaForAllocation());
}
inline std::string* Transaction::_internal_mutable_recipient() {
  
  return _impl_.recipient_.Mutable(GetArenaForAllocation());
}
inline std::string* Transaction::release_recipient() {
  // @@protoc_insertion_point(field_release:chrono_ledger_proto.Transaction.recipient)
  return _impl_.recipient_.Release();
}
inline void Transaction::set_allocated_recipient(std::string* recipient) {
  if (recipient != nullptr) {
    
  } else {
    
  }
  _impl_.recipient_.SetAllocated(recipient, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.recipient_.IsDefault()) {
    _impl_.recipient_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chrono_ledger_proto.Transaction.recipient)
}

// uint64 amount = 4;
inline void Transaction::clear_amount() {
  _impl_.amount_ = uint64_t{0u};
}
inline uint64_t Transaction::_internal_amount() const {
  return _impl_.amount_;
}
inline uint64_t Transaction::amount() const {
  // @@protoc_insertion_point(field_get:chrono_ledger_proto.Transaction.amount)
  return _internal_amount();
}
inline void Transaction::_internal_set_amount(uint64_t value) {
  
  _impl_.amount_ = value;
}
inline void Transaction::set_amount(uint64_t value) {
  _internal_set_amount(value);
  // @@protoc_insertion_point(field_set:chrono_ledger_proto.Transaction.amount)
}

// uint64 fee = 5;
inline void Transaction::clear_fee() {
  _impl_.fee_ = uint64_t{0u};
}
inline uint64_t Transaction::_internal_fee() const {
  return _impl_.fee_;
}
inline uint64_t Transaction::fee() const {
  // @@protoc_insertion_point(field_get:chrono_ledger_proto.Transaction.fee)
  return _internal_fee();
}
inline void Transaction::_internal_set_fee(uint64_t value) {
  
  _impl_.fee_ = value;
}
inline void Transaction::set_fee(uint64_t value) {
  _internal_set_fee(value);
  // @@protoc_insertion_point(field_set:chrono_ledger_proto.Transaction.fee)
}

// uint64 nonce = 6;
inline void Transaction::clear_nonce() {
  _impl_.nonce_ = uint64_t{0u};
}
inline uint64_t Transaction::_internal_nonce() const {
  return _impl_.nonce_;
}
inline uint64_t Transaction::nonce() const {
  // @@protoc_insertion_point(field_get:chrono_ledger_proto.Transaction.nonce)
  return _internal_nonce();
}
inline void Transaction::_internal_set_nonce(uint64_t value) {
  
  _impl_.nonce_ = value;
}
inline void Transaction::set_nonce(uint64_t value) {
  _internal_set_nonce(value);
  // @@protoc_insertion_point(field_set:chrono_ledger_proto.Transaction.nonce)
}

// bytes payload = 7;
inline void Transaction::clear_payload() {
  _impl_.payload_.ClearToEmpty();
}
inline const std::string& Transaction::payload() const {
  // @@protoc_insertion_point(field_get:chrono_ledger_proto.Transaction.payload)
  return _internal_payload();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Transaction::set_payload(ArgT0&& arg0, ArgT... args) {
 
 _impl_.payload_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chrono_ledger_proto.Transaction.payload)
}
inline std::string* Transaction::mutable_payload() {
  std::string* _s = _internal_mutable_payload();
  // @@protoc_insertion_point(field_mutable:chrono_ledger_proto.Transaction.payload)
  return _s;
}
inline const std::string& Transaction::_internal_payload() const {
  return _impl_.payload_.Get();
}
inline void Transaction::_internal_set_payload(const std::string& value) {
  
  _impl_.payload_.Set(value, GetArenaForAllocation());
}
inline std::string* Transaction::_internal_mutable_payload() {
  
  return _impl_.payload_.Mutable(GetArenaForAllocation());
}
inline std::string* Transaction::release_payload() {
  // @@protoc_insertion_point(field_release:chrono_ledger_proto.Transaction.payload)
  return _impl_.payload_.Release();
}
inline void Transaction::set_allocated_payload(std::string* payload) {
  if (payload != nullptr) {
    
  } else {
    
  }
  _impl_.payload_.SetAllocated(payload, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.payload_.IsDefault()) {
    _impl_.payload_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chrono_ledger_proto.Transaction.payload)
}

// bytes signature = 8;
inline void Transaction::clear_signature() {
  _impl_.signature_.ClearToEmpty();
}
inline const std::string& Transaction::signature() const {
  // @@protoc_insertion_point(field_get:chrono_ledger_proto.Transaction.signature)
  return _internal_signature();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Transaction::set_signature(ArgT0&& arg0, ArgT... args) {
 
 _impl_.signature_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chrono_ledger_proto.Transaction.signature)
}
inline std::string* Transaction::mutable_signature() {
  std::string* _s = _internal_mutable_signature();
  // @@protoc_insertion_point(field_mutable:chrono_ledger_proto.Transaction.signature)
  return _s;
}
inline const std::string& Transaction::_internal_signature() const {
  return _impl_.signature_.Get();
}
inline void Transaction::_internal_set_signature(const std::string& value) {
  
  _impl_.signature_.Set(value, GetArenaForAllocation());
}
inline std::string* Transaction::_internal_mutable_signature() {
  
  return _impl_.signature_.Mutable(GetArenaForAllocation());
}
inline std::string* Transaction::release_signature() {
  // @@protoc_insertion_point(field_release:chrono_ledger_proto.Transaction.signature)
  return _impl_.signature_.Release();
}
inline void Transaction::set_allocated_signature(std::string* signature) {
  if (signature != nullptr) {
    
  } else {
    
  }
  _impl_.signature_.SetAllocated(signature, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.signature_.IsDefault()) {
    _impl_.signature_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chrono_ledger_proto.Transaction.signature)
}

// -------------------------------------------------------------------

// Block

// bytes prev_block_hash = 1;
inline void Block::clear_prev_block_hash() {
  _impl_.prev_block_hash_.ClearToEmpty();
}
inline const std::string& Block::prev_block_hash() const {
  // @@protoc_insertion_point(field_get:chrono_ledger_proto.Block.prev_block_hash)
  return _internal_prev_block_hash();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Block::set_prev_block_hash(ArgT0&& arg0, ArgT... args) {
 
 _impl_.prev_block_hash_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chrono_ledger_proto.Block.prev_block_hash)
}
inline std::string* Block::mutable_prev_block_hash() {
  std::string* _s = _internal_mutable_prev_block_hash();
  // @@protoc_insertion_point(field_mutable:chrono_ledger_proto.Block.prev_block_hash)
  return _s;
}
inline const std::string& Block::_internal_prev_block_hash() const {
  return _impl_.prev_block_hash_.Get();
}
inline void Block::_internal_set_prev_block_hash(const std::string& value) {
  
  _impl_.prev_block_hash_.Set(value, GetArenaForAllocation());
}
inline std::string* Block::_internal_mutable_prev_block_hash() {
  
  return _impl_.prev_block_hash_.Mutable(GetArenaForAllocation());
}
inline std::string* Block::release_prev_block_hash() {
  // @@protoc_insertion_point(field_release:chrono_ledger_proto.Block.prev_block_hash)
  return _impl_.prev_block_hash_.Release();
}
inline void Block::set_allocated_prev_block_hash(std::string* prev_block_hash) {
  if (prev_block_hash != nullptr) {
    
  } else {
    
  }
  _impl_.prev_block_hash_.SetAllocated(prev_block_hash, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.prev_block_hash_.IsDefault()) {
    _impl_.prev_block_hash_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chrono_ledger_proto.Block.prev_block_hash)
}

// uint64 timestamp = 2;
inline void Block::clear_timestamp() {
  _impl_.timestamp_ = uint64_t{0u};
}
inline uint64_t Block::_internal_timestamp() const {
  return _impl_.timestamp_;
}
inline uint64_t Block::timestamp() const {
  // @@protoc_insertion_point(field_get:chrono_ledger_proto.Block.timestamp)
  return _internal_timestamp();
}
inline void Block::_internal_set_timestamp(uint64_t value) {
  
  _impl_.timestamp_ = value;
}
inline void Block::set_timestamp(uint64_t value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:chrono_ledger_proto.Block.timestamp)
}

// bytes transactions_merkle_root = 3;
inline void Block::clear_transactions_merkle_root() {
  _impl_.transactions_merkle_root_.ClearToEmpty();
}
inline const std::string& Block::transactions_merkle_root() const {
  // @@protoc_insertion_point(field_get:chrono_ledger_proto.Block.transactions_merkle_root)
  return _internal_transactions_merkle_root();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Block::set_transactions_merkle_root(ArgT0&& arg0, ArgT... args) {
 
 _impl_.transactions_merkle_root_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chrono_ledger_proto.Block.transactions_merkle_root)
}
inline std::string* Block::mutable_transactions_merkle_root() {
  std::string* _s = _internal_mutable_transactions_merkle_root();
  // @@protoc_insertion_point(field_mutable:chrono_ledger_proto.Block.transactions_merkle_root)
  return _s;
}
inline const std::string& Block::_internal_transactions_merkle_root() const {
  return _impl_.transactions_merkle_root_.Get();
}
inline void Block::_internal_set_transactions_merkle_root(const std::string& value) {
  
  _impl_.transactions_merkle_root_.Set(value, GetArenaForAllocation());
}
inline std::string* Block::_internal_mutable_transactions_merkle_root() {
  
  return _impl_.transactions_merkle_root_.Mutable(GetArenaForAllocation());
}
inline std::string* Block::release_transactions_merkle_root() {
  // @@protoc_insertion_point(field_release:chrono_ledger_proto.Block.transactions_merkle_root)
  return _impl_.transactions_merkle_root_.Release();
}
inline void Block::set_allocated_transactions_merkle_root(std::string* transactions_merkle_root) {
  if (transactions_merkle_root != nullptr) {
    
  } else {
    
  }
  _impl_.transactions_merkle_root_.SetAllocated(transactions_merkle_root, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.transactions_merkle_root_.IsDefault()) {
    _impl_.transactions_merkle_root_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chrono_ledger_proto.Block.transactions_merkle_root)
}

// uint64 height = 4;
inline void Block::clear_height() {
  _impl_.height_ = uint64_t{0u};
}
inline uint64_t Block::_internal_height() const {
  return _impl_.height_;
}
inline uint64_t Block::height() const {
  // @@protoc_insertion_point(field_get:chrono_ledger_proto.Block.height)
  return _internal_height();
}
inline void Block::_internal_set_height(uint64_t value) {
  
  _impl_.height_ = value;
}
inline void Block::set_height(uint64_t value) {
  _internal_set_height(value);
  // @@protoc_insertion_point(field_set:chrono_ledger_proto.Block.height)
}

// uint64 consensus_time = 5;
inline void Block::clear_consensus_time() {
  _impl_.consensus_time_ = uint64_t{0u};
}
inline uint64_t Block::_internal_consensus_time() const {
  return _impl_.consensus_time_;
}
inline uint64_t Block::consensus_time() const {
  // @@protoc_insertion_point(field_get:chrono_ledger_proto.Block.consensus_time)
  return _internal_consensus_time();
}
inline void Block::_internal_set_consensus_time(uint64_t value) {
  
  _impl_.consensus_time_ = value;
}
inline void Block::set_consensus_time(uint64_t value) {
  _internal_set_consensus_time(value);
  // @@protoc_insertion_point(field_set:chrono_ledger_proto.Block.consensus_time)
}

// uint32 round = 6;
inline void Block::clear_round() {
  _impl_.round_ = 0u;
}
inline uint32_t Block::_internal_round() const {
  return _impl_.round_;
}
inline uint32_t Block::round() const {
  // @@protoc_insertion_point(field_get:chrono_ledger_proto.Block.round)
  return _internal_round();
}
inline void Block::_internal_set_round(uint32_t value) {
  
  _impl_.round_ = value;
}
inline void Block::set_round(uint32_t value) {
  _internal_set_round(value);
  // @@protoc_insertion_point(field_set:chrono_ledger_proto.Block.round)
}

// repeated .chrono_ledger_proto.Transaction transactions = 7;
inline int Block::_internal_transactions_size() const {
  return _impl_.transactions_.size();
}
inline int Block::transactions_size() const {
  return _internal_transactions_size();
}
inline void Block::clear_transactions() {
  _impl_.transactions_.Clear();
}
inline ::chrono_ledger_proto::Transaction* Block::mutable_transactions(int index) {
  // @@protoc_insertion_point(field_mutable:chrono_ledger_proto.Block.transactions)
  return _impl_.transactions_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::chrono_ledger_proto::Transaction >*
Block::mutable_transactions() {
  // @@protoc_insertion_point(field_mutable_list:chrono_ledger_proto.Block.transactions)
  return &_impl_.transactions_;
}
inline const ::chrono_ledger_proto::Transaction& Block::_internal_transactions(int index) const {
  return _impl_.transactions_.Get(index);
}
inline const ::chrono_ledger_proto::Transaction& Block::transactions(int index) const {
  // @@protoc_insertion_point(field_get:chrono_ledger_proto.Block.transactions)
  return _internal_transactions(index);
}
inline ::chrono_ledger_proto::Transaction* Block::_internal_add_transactions() {
  return _impl_.transactions_.Add();
}
inline ::chrono_ledger_proto::Transaction* Block::add_transactions() {
  ::chrono_ledger_proto::Transaction* _add = _internal_add_transactions();
  // @@protoc_insertion_point(field_add:chrono_ledger_proto.Block.transactions)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::chrono_ledger_proto::Transaction >&
Block::transactions() const {
  // @@protoc_insertion_point(field_list:chrono_ledger_proto.Block.transactions)
  return _impl_.transactions_;
}

// uint32 time_tier = 8;
inline void Block::clear_time_tier() {
  _impl_.time_tier_ = 0u;
}
inline uint32_t Block::_internal_time_tier() const {
  return _impl_.time_tier_;
}
inline uint32_t Block::time_tier() const {
  // @@protoc_insertion_point(field_get:chrono_ledger_proto.Block.time_tier)
  return _internal_time_tier();
}
inline void Block::_internal_set_time_tier(uint32_t value) {
  
  _impl_.time_tier_ = value;
}
inline void Block::set_time_tier(uint32_t value) {
  _internal_set_time_tier(value);
  // @@protoc_insertion_point(field_set:chrono_ledger_proto.Block.time_tier)
}

// uint32 time_quality_score = 9;
inline void Block::clear_time_quality_score() {
  _impl_.time_quality_score_ = 0u;
}
inline uint32_t Block::_internal_time_quality_score() const {
  return _impl_.time_quality_score_;
}
inline uint32_t Block::time_quality_score() const {
  // @@protoc_insertion_point(field_get:chrono_ledger_proto.Block.time_quality_score)
  return _internal_time_quality_score();
}
inline void Block::_internal_set_time_quality_score(uint32_t value) {
  
  _impl_.time_quality_score_ = value;
}
inline void Block::set_time_quality_score(uint32_t value) {
  _internal_set_time_quality_score(value);
  // @@protoc_insertion_point(field_set:chrono_ledger_proto.Block.time_quality_score)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace chrono_ledger_proto

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ledger_2eproto
